---
# tasks file for novell-audit-platform-agent

- name: install Platform Agent on SLES
  become: true
  zypper: 
    name='https://eu2idmcloud5049.blob.core.windows.net:443/software/novell-AUDTplatformagent-2.0.2-77.x86_64.rpm'
    state=present
    disable_gpg_check=yes
  when: ansible_distribution == "SLES"
  tags:
    - software
 
- name: ensure novell_audit_group exists
  become: true
  group:
    name="{{ novell_audit_group }}"
    state=present
  tags:
    - groups
 
- name: deploy logevent.conf
  become: true
  template: 
    src=logevent.conf.j2 
    dest=/etc/logevent.conf
    owner=root 
    group="{{ novell_audit_group }}" 
    mode=0664 
  notify: 
    - kill lcache
    - kill jlcache
  tags:
    - template
    
- name: deploy logrotate config
  become: true
  template: 
    src=novell-audit.logrotate.j2 
    dest=/etc/logrotate.d/novell-audit
    owner=root 
    group="{{ novell_audit_group }}"
    mode=0664 
  tags:
    - template

- name: create naudit directories
  become: true
  file:
    path={{ item }}
    state=directory
    owner=root 
    group="{{ novell_audit_group }}" 
    mode=0770
  with_items:
    - /var/opt/novell/naudit
    - /var/opt/novell/naudit/cache 
    - /var/opt/novell/naudit/jcache
  tags:
    - rights
   
- name: create nproduct.log
  become: true
  file:
    path=/var/opt/novell/naudit/nproduct.log
    state=present
    owner=root 
    group="{{ novell_audit_group }}"
    mode=0660
  tags:
    - rights
